language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage==4.5.4
script:
  - echo "My Python Test"
after_success:
  - coveralls

